#!/usr/bin/env python3
import argparse
import requests
import sys
from os import path

try:
    with open(path.join(sys.path[0], "ifttt_key"), "r") as f:
        ifttt_api_key = f.readline()
except Exception:
    raise SystemExit("Failed to import IFTTT API key. API key file is missing / insufficient permissions")

### Img URLs defined here ###
statuses = {
    "message": "https://www.iconsdb.com/icons/preview/black/message-2-xxl.png",
    "info": "https://img.icons8.com/pastel-glyph/2x/info.png",
    "warning": "https://www.citypng.com/public/uploads/preview/png-orange-error-warning-icon-11639742699bjl3rmwkvw.png",
    "error": "https://iconsplace.com/wp-content/uploads/_icons/ff0000/256/png/error-icon-14-256.png",
    "webserver-dosattack": "https://i.ibb.co/bLsbryD/hack-icon.png",
    "weatherstation-error": "https://i.ibb.co/ftJLCrs/30262987-1-Cropped-adobespark.png",
    "weatherstation-success": "https://i.ibb.co/ncr7cGT/cute-blue-cloud-icon-isolated-260nw-1411271507-Cropped-adobespark.png",
    "ups-powerloss": "https://i.ibb.co/cFvNbMj/power-loss.png",
    "ups-powerrestored": "https://i.ibb.co/XsHKPV3/power-restored.png",
    "backup-started": "https://cdn-icons-png.flaticon.com/512/2970/2970590.png",
}

### Def values for args ###
defaults = {"title": "Test Message", "message": "Hello World!", "status": "message"}

### Init command line arguments ###
parser = argparse.ArgumentParser(description="Sends messages to my iPhone via the IFTTT app")
parser.add_argument("-t", "--title")
parser.add_argument("-m", "--message")
parser.add_argument("-s", "--status")
args = parser.parse_args()

### Add defualt args ###
newargs = {}
for arg in vars(args):
    if not getattr(args, arg):
        newargs[arg] = defaults[arg]
    else:
        newargs[arg] = getattr(args, arg)
if newargs["status"] not in statuses.keys():
    raise SystemExit("Not a valid status.")
newargs["imageurl"] = statuses[newargs["status"]]
newargs.pop("status")

### Payload init ###
payload = {}
vals = list(newargs.values())
for i in range(len(vals)):
    payload[f"value{i + 1}"] = vals[i]

### Request with JSON payload ###
try:
    r = requests.get(f"https://maker.ifttt.com/trigger/message_recieved/with/key/{ifttt_api_key}", params=payload)
except Exception:
    raise SystemExit("Request failed - connectivity issues?")
